version: '3.6'
services:
  api:
    build: 
      context: .
      dockerfile: API/Dockerfile
    image: digitalexcellence/api
    ports: 
      - 5000:80
    depends_on:
      - db
    networks:
      - mssql-network
      - web 
    environment:
      - ConnectionStrings__DefaultConnection=${STAGING_CONNECTION_STRING} 
      - App__Frontend__FrontendUrl=https://staging.dex.software 
      - App__Frontend__ClientId=${STAGING_API_FRONTEND_CLIENT_ID}
      - App__Frontend__ClientSecret=${STAGING_API_FRONTEND_CLIENT_SECRET}  
      - App__IdentityServer__IdentityUrl=https://identity.staging.dex.software
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.staging.dex.software
      - traefik.docker.network=web
      - traefik.port=5000
      
  db:
    build: ./Data
    image: digitalexcellence/database
    ports:
      - 1433:1433
    networks:
      mssql-network:
        ipv4_address: 172.16.238.2
    environment:
      - MSSQL_SA_PASSWORD=${STAGING_DATABASE_PASSWORD}

  identity:
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    image: digitalexcellence/identity
    ports: 
      - 5005:80
    networks:
      - web
    environment:
      - App__Self__JwtAuthority=https://staging.dex.software/ 
      - App__Self__IdentityApplications=${STAGING_IDENTITY_APPLICATIONS}
      - App__Api__DeXApiUrl=https://staging.api.dex.software 
      - App__Frontend__RedirectUrisFrontend=[ "https://staging.dex.software/auth-callback" ]
      - App__Frontend__PostLogoutUrisFrontend=[ "https://staging.dex.software/" ]
    labels:
      - traefik.backend=identity
      - traefik.frontend.rule=Host:identity.staging.dex.software
      - traefik.docker.network=web
      - traefik.port=5005

networks:
  mssql-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
  web:
    external:
      name: web
