name: staging-deployment

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      STAGING_CONNECTION_STRING: ${{ secrets.STAGING_CONNECTION_STRING }}
      STAGING_API_FRONTEND_CLIENT_ID: ${{ secrets.STAGING_API_FRONTEND_CLIENT_ID }}
      STAGING_API_FRONTEND_CLIENT_SECRET: ${{ secrets.STAGING_API_FRONTEND_CLIENT_SECRET }}
      STAGING_DATABASE_PASSWORD: ${{ secrets.STAGING_DATABASE_PASSWORD }}
      STAGING_IDENTITY_APPLICATIONS: ${{ secrets.STAGING_IDENTITY_APPLICATIONS }}

    steps:
      - uses: actions/checkout@v1
      - name: Run docker compose build
        run: docker-compose -f docker-compose.staging.yml build 
      - name: Push docker images to dockerhub
        run: docker-compose -f docker-compose.staging.yml push
      
